### **LMC targets**

In this notebook, we calculate the target LMC position, velocity and orientation of the disc

TLDR: 

(x, y, z) in kpc (-0.61436097, -41.02036742, -26.83297465)
            
(v_x, v_y, v_z) in km / s (-69.85587904, -221.68751413, 214.15271769)

In [2]:
# import packages
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

from astropy import units as u
from astropy import coordinates as coord
from astropy.coordinates import SkyCoord

import astropy

In [3]:
# LMC values compiled from https://arxiv.org/pdf/2304.09136.pdf (Vasiliev 2023)

lmc_ra = 81.28 * u.deg # https://arxiv.org/pdf/2012.01771.pdf (Luri, Gaia Collab 2021)
lmc_dec = -69.78 * u.deg # https://arxiv.org/pdf/2012.01771.pdf (Luri, Gaia Collab 2021)
lmc_dist = 49.6 * u.kpc # kpc # https://www.nature.com/articles/s41586-019-0999-4 (Pietrzynski et al 2019)
lmc_pmra = 1.858 * u.mas/u.yr # mas/yr # https://arxiv.org/pdf/2012.01771.pdf (Luri, Gaia Collab 2021)
lmc_pmdec = 0.385 * u.mas/u.yr # mas/yr # https://arxiv.org/pdf/2012.01771.pdf (Luri, Gaia Collab 2021)
lmc_vrad = 262.2 * u.km/u.s # km/s # https://iopscience.iop.org/article/10.1086/343775 (van der Marel et al 2002)

# LMC disc values from Luri, Gaia Collab 2021 (used above): https://arxiv.org/pdf/2012.01771.pdf
lmc_disc_ra = 81.28 * u.deg
lmc_disc_dec = -69.78 * u.deg
lmc_mx0 = 1.858 * u.mas/u.yr
lmc_my0 = 0.385 * u.mas/u.yr
lmc_mz0 = 1.115 * u.mas/u.yr

# LMC orientation from Choi et al 2018 https://arxiv.org/abs/1804.07765
# rotation matrices given in van der Marel et al 2002 and implemented further below
lmc_i = 26 * u.deg # inclination
lmc_theta = 149 * u.deg # line-of-node position angle




In [4]:
# converting these values to Galactocentric values using astropys coordinates package
# Galactocentric coordinates
galcen = coord.Galactocentric()
print(f'astropy {astropy.__version__}')
print(galcen)
print(galcen.frame_attribute_references)

""" Last updated print outputs 2023/11/13 (astropy 5.3.4)

<Galactocentric Frame (galcen_coord=<ICRS Coordinate: (ra, dec) in deg (266.4051, -28.936175)>, 
                        galcen_distance=8.122 kpc, 
                        galcen_v_sun=(12.9, 245.6, 7.78) km / s, 
                        z_sun=20.8 pc, roll=0.0 deg)>
                    
{'galcen_coord': 'https://ui.adsabs.harvard.edu/abs/2004ApJ...616..872R', 
'galcen_distance': 'https://ui.adsabs.harvard.edu/abs/2018A%26A...615L..15G', 
'galcen_v_sun': ['https://ui.adsabs.harvard.edu/abs/2018RNAAS...2..210D', 
                'https://ui.adsabs.harvard.edu/abs/2018A%26A...615L..15G', 
                'https://ui.adsabs.harvard.edu/abs/2004ApJ...616..872R'], 
'z_sun': 'https://ui.adsabs.harvard.edu/abs/2019MNRAS.482.1417B', 
'roll': None}
"""

# LMC object
lmc_skycoord = SkyCoord(
                    ra=lmc_ra, 
                    dec=lmc_dec, 
                    distance=lmc_dist, 
                    pm_ra_cosdec=lmc_pmra, 
                    pm_dec=lmc_pmdec, 
                    radial_velocity=lmc_vrad, 
                    frame='icrs', 
                    obstime="J2016"
                )

lmc_galcen = lmc_skycoord.transform_to(galcen)
print(lmc_galcen)

""" Last updated print output 2023/11/13 (astropy 5.3.4)
<SkyCoord (Galactocentric: galcen_coord=<ICRS Coordinate: (ra, dec) in deg (266.4051, -28.936175)>, 
            galcen_distance=8.122 kpc, galcen_v_sun=(12.9, 245.6, 7.78) km / s, z_sun=20.8 pc, roll=0.0 deg): 
            (x, y, z) in kpc (-0.61436097, -41.02036742, -26.83297465)
            (v_x, v_y, v_z) in km / s (-69.85587904, -221.68751413, 214.15271769)>
"""


astropy 5.3.4
<Galactocentric Frame (galcen_coord=<ICRS Coordinate: (ra, dec) in deg
    (266.4051, -28.936175)>, galcen_distance=8.122 kpc, galcen_v_sun=(12.9, 245.6, 7.78) km / s, z_sun=20.8 pc, roll=0.0 deg)>
{'galcen_coord': 'https://ui.adsabs.harvard.edu/abs/2004ApJ...616..872R', 'galcen_distance': 'https://ui.adsabs.harvard.edu/abs/2018A%26A...615L..15G', 'galcen_v_sun': ['https://ui.adsabs.harvard.edu/abs/2018RNAAS...2..210D', 'https://ui.adsabs.harvard.edu/abs/2018A%26A...615L..15G', 'https://ui.adsabs.harvard.edu/abs/2004ApJ...616..872R'], 'z_sun': 'https://ui.adsabs.harvard.edu/abs/2019MNRAS.482.1417B', 'roll': None}
<SkyCoord (Galactocentric: galcen_coord=<ICRS Coordinate: (ra, dec) in deg
    (266.4051, -28.936175)>, galcen_distance=8.122 kpc, galcen_v_sun=(12.9, 245.6, 7.78) km / s, z_sun=20.8 pc, roll=0.0 deg): (x, y, z) in kpc
    (-0.61436097, -41.02036742, -26.83297465)
 (v_x, v_y, v_z) in km / s
    (-69.85587904, -221.68751413, 214.15271769)>


' Last updated print output 2023/11/13 (astropy 5.3.4)\n<SkyCoord (Galactocentric: galcen_coord=<ICRS Coordinate: (ra, dec) in deg (266.4051, -28.936175)>, \n            galcen_distance=8.122 kpc, galcen_v_sun=(12.9, 245.6, 7.78) km / s, z_sun=20.8 pc, roll=0.0 deg): \n            (x, y, z) in kpc (-0.61436097, -41.02036742, -26.83297465)\n            (v_x, v_y, v_z) in km / s (-69.85587904, -221.68751413, 214.15271769)>\n'

(x, y, z) in kpc
    (-0.61436097, -41.02036742, -26.83297465)
 (v_x, v_y, v_z) in km / s
    (-69.85587904, -221.68751413, 214.15271769)>

#### **LMC rotation**

A very good description of rotation matrices w.r.t. the LMC is given in van der Marel et al 2002. I implement these here


In [26]:
def cartesian_LMC_to_galactocentric(x_LMC, y_LMC, z_LMC, i_LMC=26*u.deg, theta_LMC=149*u.deg):
    """
    Convert  LMC cartesian coordinates to Galactocentric cartesian coordinates
    """
    # rotation matrices from van der Marel et al 2002
    i_LMC = i_LMC.to(u.rad).value
    theta_LMC = theta_LMC.to(u.rad).value
    
    R_LMC = np.array([[np.cos(theta_LMC), -np.sin(theta_LMC) * np.cos(i_LMC), -np.sin(theta_LMC) * np.sin(i_LMC)],
                      [np.sin(theta_LMC), np.cos(theta_LMC) * np.cos(i_LMC), np.cos(theta_LMC) * np.sin(i_LMC)],
                      [0, -np.sin(i_LMC), np.cos(i_LMC)]])
    
    vec_LMC = np.vstack((x_LMC, y_LMC, z_LMC))
    
    return np.matmul(R_LMC, vec_LMC)
    

In [28]:
# test that cartesian_LMC_to_galactocentric_position works for single values and arrays
a, b, c = 1, 2, 3
print("single values\n", cartesian_LMC_to_galactocentric(a, b, c))

a = np.array([1,2,3,4]) 
b = np.array([2,3,4,5]) 
c = np.array([3,4,5,6])

print("arrays\n", cartesian_LMC_to_galactocentric(a, b, c))

single values
 [[-2.46032711]
 [-2.1530679 ]
 [ 1.81963985]]
arrays
 [[-2.46032711 -4.00618539 -5.55204368 -7.09790197]
 [-2.1530679  -2.7842041  -3.4153403  -4.04647651]
 [ 1.81963985  2.28006274  2.74048564  3.20090854]]
